'use client'

import { useState } from 'react'

const FAQ_ITEMS = [
  {
    q: 'Is Stitch Pattern Maker really free?',
    a: 'Yes — completely free, with no hidden costs. Upload a photo, adjust the settings, and download your PDF pattern without creating an account.',
  },
  {
    q: 'Does it process my photo on the server?',
    a: 'No. Everything runs entirely in your browser. Your images are never uploaded to any server, so your photos stay private.',
  },
  {
    q: 'What image formats are supported?',
    a: 'JPEG, PNG, WebP, and GIF are all supported. For best results use a photo with clear subjects and good contrast. Portraits, pets, landscapes, and simple illustrations all work well.',
  },
  {
    q: 'How many DMC thread colors can I use?',
    a: 'You can set anywhere from 5 to 80 colors. For beginners, 10–20 colors keeps the project manageable. Increasing the color count produces more detailed patterns that closely match the original photo.',
  },
  {
    q: 'Can I print the pattern?',
    a: 'Yes. Use the PDF export button to download a print-ready file. Print at 100% scale on A4 paper — the grid lines, color symbols, and DMC thread list are all included.',
  },
  {
    q: 'What size pattern should I generate?',
    a: 'Start with 50×50 to 100×100 stitches. At 14-count Aida fabric that gives a finished piece of roughly 9–18 cm — ideal for a first project. You can go larger once you are comfortable with the process.',
  },
  {
    q: 'What is the "color separation" setting?',
    a: 'Color separation merges thread colors that look very similar (measured in CIE LAB color space). Setting it to Medium or Strong reduces the total number of threads you need to buy and makes it easier to tell colors apart while stitching.',
  },
  {
    q: 'Can I use generated patterns for commercial products?',
    a: 'Patterns generated by this tool are yours to use however you like. Note that the underlying photo must be one you own or have rights to — the tool does not grant rights to third-party images.',
  },
]

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: FAQ_ITEMS.map(({ q, a }) => ({
    '@type': 'Question',
    name: q,
    acceptedAnswer: { '@type': 'Answer', text: a },
  })),
}

export default function HomeFAQ() {
  const [open, setOpen] = useState<number | null>(null)

  return (
    <section className="max-w-3xl mx-auto px-4 sm:px-9 pb-20">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* Section header */}
      <div className="flex items-center gap-2.5 mb-7">
        <span className="text-[10px] uppercase tracking-[0.18em] text-sage-400 font-light">FAQ</span>
        <div className="h-px flex-1 bg-linen-300/30" />
      </div>
      <h2 className="font-playfair text-[26px] text-warm-700 mb-7 leading-snug">
        Frequently Asked Questions
      </h2>

      <div className="space-y-2">
        {FAQ_ITEMS.map(({ q, a }, i) => {
          const isOpen = open === i
          return (
            <div
              key={q}
              className="bg-linen-50/70 border border-linen-300/25 rounded-card overflow-hidden"
            >
              <button
                type="button"
                onClick={() => setOpen(isOpen ? null : i)}
                className="w-full flex items-center justify-between px-6 py-4 cursor-pointer
                           text-[14px] text-warm-600 font-normal text-left
                           hover:bg-linen-100/50 transition-colors"
              >
                <h3 className="font-normal leading-snug">{q}</h3>
                <span
                  className="text-sage-400 text-lg leading-none ml-4 flex-shrink-0 transition-transform duration-200"
                  style={{ transform: isOpen ? 'rotate(45deg)' : 'none' }}
                >
                  +
                </span>
              </button>
              {isOpen && (
                <div className="px-6 pb-5 pt-1 text-[13px] text-warm-500 font-light leading-relaxed
                                border-t border-linen-300/20">
                  {a}
                </div>
              )}
            </div>
          )
        })}
      </div>
    </section>
  )
}
